version: '3'

services:
  postgres:
    image: postgres:latest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: postgres-mines
    ports:
      - "5432:5432"
    env_file:
      - .env